project:
  type: website

website:
  title: "Chloe Cheng"
  navbar:
    left:
      - href: index.qmd
        text: home
      - href: research.qmd
        text: research
      - href: art.qmd
        text: art
      - href: about.qmd
        text: about
  search: false

format:
  html:
    include-in-header: _sidebar.html
    css: styles.css
    toc: true
    toc-location: right